name: Build and Deploy to VPS

on:
  workflow_dispatch:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'  # Every day at midnight UTC

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Setup Node.js (latest LTS)
      uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Install pnpm
      run: |
        corepack enable
        corepack prepare pnpm@latest --activate

    - name: Install dependencies
      run: pnpm install

    - name: Build site
      run: pnpm build
      env:
        WEBMENTION_IO_TOKEN: ${{ secrets.WEBMENTION_IO_TOKEN }}

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy public/ via rsync
      run: |
        rsync -rtvzP ./public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/parham.dev

    - name: Restart Caddy
      run: |
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "systemctl restart caddy"
